<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class DogsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('dogs')->truncate();
        DB::table('dogs')->insert([
            [
                'id'=>1,
                'name'=>'Pug Xệ',
                'price'=>'13000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>1,
                'breedType'=>1,
                'color'=>'Trắng',
                'thumbnail'=>'ngoai-hinh-cho-pug_fbudvh',
                'description'=>'Chú chó Pug có chiều cao từ 25 - 35 cm và có cân nặng khoảng 6 - 10kg. Sở hữu chiều cao lùn và thân hình to mập nên chó Pug có thân hình vuông. Lưng Pug thẳng, không lõm cũng không căng nên chúng có dáng đi khá oai vệ và vững chắc. Chó Pug có làn da khá mềm và mỗi khi vuốt ve chúng sẽ cảm thấy vô cùng dễ chịu. ',
                'detail'=>'Đã qua huấn luyện, ngày ăn 3 bữa, thức ăn là Thức Ăn Hạt Cho Chó Royal Canin Pug Adult,Thức ăn cho chó trưởng thành DreamFood ... ',
                'mother_id'=>1,
                'father_id'=>1,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>2,
                'name'=>'Yi',
                'price'=>'10000000',
                'birthday'=>'2019-05-10',
                'gender'=>2,
                'category_id'=>2,
                'breedType'=>1,
                'color'=>'Đen',
                'thumbnail'=>'cho-pug-mat-xe_gcno1p',
                'description'=>'Chó Pug sở hữu những đôi mắt to tròn và lồi, những chú chó Pug thuần chủng mắt sẽ có màu sẫm. Tai chúng luôn luôn cụp và to. Khuôn miệng chúng khá rộng, phần xương hàm to và chắc khỏe. Riêng hàm dưới sẽ hơi nhô so với hàm trên.Trái với khuôn mặt dữ dằn và nghiêm túc, tính cách chó Pug lại rất hiền lành và hòa đồng. Hơn nữa, chúng cực kỳ thông minh, lanh lợi, trung thành và rất thân thiện với con người và những chú chó khác.',
                'detail'=>'Đã qua huấn luyện, rất ngoan ngoãn và nghe lời của chủ',
                'mother_id'=>1,
                'father_id'=>1,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>3,
                'name'=>'Ben',
                'price'=>'9000000',
                'birthday'=>'2019-05-10',
                'gender'=>2,
                'category_id'=>3,
                'breedType'=>2,
                'color'=>'Vàng',
                'thumbnail'=>'cho-poodle-teacup_hdr9ps',
                'description'=>'Chó Poodle là giống chó săn vịt cực đáng yêu, loài Poodle hiện phổ biến với 3 loại là Toy Poodle, Mini Poodle và Standard Poodle và đều có tuổi thọ từ 12 - 15 năm. Còn hai kích thước không được công nhận là Tiny và Teacup thì có tuổi thọ khá ngắn, từ 5 - 8 năm.',
                'detail'=>'Rất đáng yêu, thông minh, huấn luyện kĩ càng về các kĩ thuật',
                'mother_id'=>2,
                'father_id'=>2,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>4,
                'name'=>'Panda',
                'price'=>'11000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>4,
                'breedType'=>2,
                'color'=>'Trắng',
                'thumbnail'=>'cho-poodle-thong-minh-thu-hai-the-gioi_efv5yh',
                'description'=>'Chó Poodle được biết đến ở Tây Âu vào khoảng 400 năm trước và chúng chính là hậu duệ của các giống chó như French Water Dog, Hungarian Water Hound và Barbet. Ngày nay, con người đã lai tạo giống chó săn vịt này thành một hình tượng quý tộc và xinh xắn, trở thành chú chó được nhiều người yêu thích.',
                'detail'=>'Thông minh, nhanh nhẹn, thân thiện',
                'mother_id'=>2,
                'father_id'=>2,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>5,
                'name'=>'PêĐô',
                'price'=>'5000000',
                'birthday'=>'2019-05-10',
                'gender'=>2,
                'category_id'=>5,
                'breedType'=>3,
                'color'=>'Tam thể',
                'thumbnail'=>'cho-beagle-1_frtb2x',
                'description'=>'Chó Beagle xuất hiện cách đây từ khoảng 2400 năm về trước và đó là kết quả của sự lai tạo giữa chó bản địa Anh và chó săn thỏ Talbot. Khoảng thế kỷ XIX, Beagle du nhập đến Anh Quốc và dần trở nên phổ biến khắp châu Âu.',
                'detail'=>'Đã qua huấn luyện, tinh nhạy và nhanh nhẹn',
                'mother_id'=>3,
                'father_id'=>3,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>6,
                'name'=>'Tetdy',
                'price'=>'12500000',
                'birthday'=>'2019-05-10',
                'gender'=>2,
                'category_id'=>6,
                'breedType'=>3,
                'color'=>'Tam Thể',
                'thumbnail'=>'cho-beagle_tdy3dz',
                'description'=>'Sở hữu một ngoại hình đáng yêu và thu hút nên chó Beagle được rất nhiều người yêu thích và muốn sở hữu chúng để là thú cưng. Chúng có chiều cao khoảng 33 - 41cm ở độ tuổi trưởng thành và cân nặng từ 10 - 11kg với chó đực, 9 - 10kg với chó cái. Chúng có thân hình vuông vắn, cứng cáp và nổi bật với bộ lông tam thể mượt mà cùng đôi tai cụp đặc trưng.
Chó Beagle là loài chó vui nhộn và năng động, trông chúng lúc nào cũng tràn đầy năng lực và có vẻ như chúng rất thích các hoạt động ngoài trời. Nhưng tuy nhiên chúng có bản tính săn mồi, có thể làm hại những vật nuôi khác như mèo, thỏ, hamster,...',
                'detail'=>'Hiền lành, rất nghe lời chủ',
                'mother_id'=>3,
                'father_id'=>3,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>7,
                'name'=>'HuaLa',
                'price'=>'9500000',
                'birthday'=>'2019-05-10',
                'gender'=> 2,
                'category_id'=>7,
                'breedType'=>4,
                'color'=>'Trắng',
                'thumbnail'=>'Teacup-Chihuahua_ut5ds7',
                'description'=>'Chihuahua là chú chó nhỏ nhất trong mọi loài chó trên thế giới và cũng là giống chó lâu đời nhất ở châu Mỹ. Chú chó này có nguồn gốc từ Mexico nhưng lại được cả thế giới biết đến nhờ Trung Quốc. Tên của chúng được lấy từ tên một bang của Mexico, bang Chihuahuan, là nơi mà chú chó được tìm thấy.',
                'detail'=>'tinh nghịch, và sủa nhiều khi gặp người lạ',
                'mother_id'=>4,
                'father_id'=>4,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>8,
                'name'=>'TiTi',
                'price'=>'10000000',
                'birthday'=>'2019-05-10',
                'gender'=>2,
                'category_id'=>8,
                'breedType'=>4,
                'color'=>'Vàng Nâu',
                'thumbnail'=>'dac-diem-cho-chihuahua_h6wjda',
                'description'=>'Chó Chihuahua là giống chó nhỏ con có đầu tròn và mõm ngắn. Đôi mắt chúng to, tròn và lồi. Đôi tai của Chihuahua to đùng luôn trong trạng thái vểnh lên. ',
                'detail'=>'Nhanh nhẹn,T tuy nhỏ con nhưng TiTi có tính nóng nảy',
                'mother_id'=>4,
                'father_id'=>4,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>9,
                'name'=>'Bự',
                'price'=>'20000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>9,
                'breedType'=>5,
                'color'=>'Đen',
                'thumbnail'=>'tj0s4r51bfgpmxq3fjdd',
                'description'=>'Chó Bully xuất hiện từ những năm 1995 và là hậu duệ của chó Pitbull nhưng chúng sở hữu vẻ ngoài đô hơn và cơ bắp hơn. Đây là giống chó cảnh đang được yêu thích tại Việt Nam.',
                'detail'=>'Nhìn đồ sộ nhưng rất nhanh nhẹn, hiền lành',
                'mother_id'=>5,
                'father_id'=>5,
                'status'=>1,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>10,
                'name'=>'Huk',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>10,
                'breedType'=>5,
                'color'=>'Trắng',
                'thumbnail'=>'cho-bully_pruhgc',
                'description'=>'Bully American là một trong những loài chó ngoại mới du nhập vào Việt Nam khoảng 6 năm trở lại đây. Do cơn sốt Bully chưa có dấu hiệu dừng lại nên cho tới thời điểm hiện nay, giá chó Bully vẫn ở mức tương đối cao.',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>5,
                'father_id'=>5,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>11,
                'name'=>'Katy',
                'price'=>'21000000',
                'birthday'=>'2018-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'IMG_9759_di3ysm',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>12,
                'name'=>'Kem',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'IMG_0413_fgpzvx',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>13,
                'name'=>'Jerry',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'IMG_1489_vub98f',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>14,
                'name'=>'Lee',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'098_mkl2sq',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>15,
                'name'=>'Jim',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'IMG_9755_mxocir',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>16,
                'name'=>'Puppy',
                'price'=>'21000000',
                'birthday'=>'2019-05-10',
                'gender'=>1,
                'category_id'=>0,
                'breedType'=>6,
                'color'=>'Trắng đen',
                'thumbnail'=>'052_i5xcxu',
                'description'=>'',
                'detail'=>'Rất ngoan ngoãn và nghe lời chủ',
                'mother_id'=>0,
                'father_id'=>0,
                'status'=>0,
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],

        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
