<?php


use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\ServiceProvider;

class ImgTimelineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('imgtimelines')->truncate();
        DB::table('imgtimelines')->insert([
            [
                'id' => 1,
                'thumbnail' => '1493569_351417164996387_524079409_o_m1arbz',
                'thumbnail_by'=> 11,
                'title'=>'Có ai ngắm mưa cùng Katy không ????',
                'description'=>'Nay trời mưa to quá, Katy phải ở nhà ngắm mưa rơi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'thumbnail' => '11053130_1608767839359261_1769128936354867755_o_l4wazx',
                'thumbnail_by'=> 11,
                'title'=>'Katy đang cảm thấy thèm ăn',
                'description'=>'Cho Katy ăn gì bây giờ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'thumbnail' => '11731883_572964042841697_6589992666285815759_o_el9cph',
                'thumbnail_by'=> 11,
                'title'=>'Katy cảm thấy hưng phấn',
                'description'=>'Mọi người chơi với Katy đi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'thumbnail' => 'IMG_1156_vs7ddn',
                'thumbnail_by'=> 11,
                'title'=>'Katy chuẩn bị đi ngủ',
                'description'=>'Katy chúc các bạn ngủ ngon',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'thumbnail' => 'IMG_1262_ntoocc',
                'thumbnail_by'=> 11,
                'title'=>'Katy đi dạo',
                'description'=>'Katy mệt quá, Katy nghỉ một tí',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'thumbnail' => 'IMG_1155_fsibvq',
                'thumbnail_by'=> 11,
                'title'=>'Katy đang cảm thấy buồn chán',
                'description'=>'Ai làm Katy vui đi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'thumbnail' => 'IMG_1151_myjfo7',
                'thumbnail_by'=> 11,
                'title'=>'Katy cảm thấy yếu đuối ',
                'description'=>'Ai làm Katy buồn thế',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'thumbnail' => 'IMG_1159_pyl3p6',
                'thumbnail_by'=> 11,
                'title'=>'Katy làm đẹp',
                'description'=>'Các bạn cảm thấy Katy thế nào ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'thumbnail' => 'IMG_1461_mwa1wc',
                'thumbnail_by'=> 11,
                'title'=>'Katy đội mũ',
                'description'=>'Các bạn có cảm thấy Katy đáng yêu không ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'thumbnail' => 'IMG_1541_wcrsrt',
                'thumbnail_by'=> 11,
                'title'=>'Katy đang cảm thấy vui',
                'description'=>'Hôm nay Katy rất vui',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'thumbnail' => 'IMG_3062_gk63nd',
                'thumbnail_by'=> 11,
                'title'=>'Katy ngồi tắm nắng',
                'description'=>'Có ai tắm nắng cùng không nhỉ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'thumbnail' => 'IMG_3047_gq746k',
                'thumbnail_by'=> 11,
                'title'=>'Katy ngồi tắm nắng',
                'description'=>'Có ai tắm nắng cùng không nhỉ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'thumbnail' => 'IMG_3065_nc0v3j',
                'thumbnail_by'=> 11,
                'title'=>'Katy ngồi tắm nắng',
                'description'=>'Có ai tắm nắng cùng không nhỉ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'thumbnail' => 'IMG_3066_oqra0b',
                'thumbnail_by'=> 11,
                'title'=>'Katy ngồi tắm nắng',
                'description'=>'Có ai tắm nắng cùng không nhỉ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'thumbnail' => 'IMG_3027_hycbwb',
                'thumbnail_by'=> 11,
                'title'=>'Katy ngồi tắm nắng',
                'description'=>'Có ai tắm nắng cùng không nhỉ ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'thumbnail' => 'IMG_3016_dzuw4l',
                'thumbnail_by'=> 11,
                'title'=>'Katy chuẩn bị được đi xem phim',
                'description'=>'Katy vui quá',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 17,
                'thumbnail' => 'IMG_9699_kkjt6t',
                'thumbnail_by'=> 11,
                'title'=>'Katy cảm thấy mệt',
                'description'=>'Katy nằm nghỉ tí',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'thumbnail' => 'IMG_9643_vhm2rj',
                'thumbnail_by'=> 11,
                'title'=>'Katy chơi đồ chơi',
                'description'=>'Chơi vui quá có ai chơi cùng mình không ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 19,
                'thumbnail' => 'IMG_9748_jp3rvn',
                'thumbnail_by'=> 11,
                'title'=>'Katy chơi đồ chơi',
                'description'=>'Chơi vui quá có ai chơi cùng mình không ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 20,
                'thumbnail' => 'IMG_9782_iitchl',
                'thumbnail_by'=> 11,
                'title'=>'Katy sắp đẻ',
                'description'=>'Katy bị mệt vì sắp đẻ ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'thumbnail' => 'IMG_0585_us3gyi',
                'thumbnail_by'=> 12,
                'title'=>'Kem chơi đồ chơi',
                'description'=>'Chơi vui quá có ai chơi cùng Kem không ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'thumbnail' => 'IMG_0413_fgpzvx',
                'thumbnail_by'=> 12,
                'title'=>'Kem buồn ngủ quá',
                'description'=>'Kem đi ngủ đây chào mọi người',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'thumbnail' => 'IMG_3376_blyqxk',
                'thumbnail_by'=> 12,
                'title'=>'Kem trầm tư',
                'description'=>'Kem đang nghĩ là tối nay ăn gì ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 24,
                'thumbnail' => 'IMG_1325_iacbmd',
                'thumbnail_by'=> 12,
                'title'=>'Kem đi tắm',
                'description'=>'Kem đi tắm rửa để chuẩn bị đi chơi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'thumbnail' => 'IMG_1432_z8yweg',
                'thumbnail_by'=> 12,
                'title'=>'Kem được mẹ bế',
                'description'=>'Kem được chơi tàu lượn cùng mẹ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 26,
                'thumbnail' => 'IMG_1433_fsfzwx',
                'thumbnail_by'=> 12,
                'title'=>'Kem được mẹ bế',
                'description'=>'Kem được chơi tàu lượn cùng mẹ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'thumbnail' => 'IMG_1489_vub98f',
                'thumbnail_by'=> 13,
                'title'=>'Jerry nóng quá',
                'description'=>'Jerry muốn dùng quạt',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'thumbnail' => 'IMG_1492_rkvnn9',
                'thumbnail_by'=> 13,
                'title'=>'Jerry ngứa răng',
                'description'=>'Jerry cắn cái quạt',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'thumbnail' => 'IMG_5430_f7mnlm',
                'thumbnail_by'=> 13,
                'title'=>'Jerry nằm ngủ',
                'description'=>'Jerry cảm thấy thoải mái quá',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'thumbnail' => 'IMG_5443_zkkncc',
                'thumbnail_by'=> 13,
                'title'=>'Jerry được chụp ảnh',
                'description'=>'Jerry ngại quá',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'thumbnail' => 'IMG_5536_hhm5yh',
                'thumbnail_by'=> 13,
                'title'=>'Jerry nằm chơi',
                'description'=>'Mát quá Jerry chuẩn bị ngủ luôn',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'thumbnail' => 'IMG_5554_ghmm5j',
                'thumbnail_by'=> 13,
                'title'=>'Jerry nằm chơi',
                'description'=>'Jerry nằm chơi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'thumbnail' => 'IMG_5547_u6femy',
                'thumbnail_by'=> 13,
                'title'=>'Jerry buồn ngủ',
                'description'=>'Jerry đi ngủ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'thumbnail' => 'IMG_5558_ipzo0p',
                'thumbnail_by'=> 13,
                'title'=>'Jerry bị ngứa',
                'description'=>'Ngứa quá, Jerry ngãi ngứa',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'thumbnail' => '052_i5xcxu',
                'thumbnail_by'=> 14,
                'title'=>'Lee lạnh',
                'description'=>'Lee kéo chăn để đắp',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'thumbnail' => '057_r5ekgb',
                'thumbnail_by'=> 14,
                'title'=>'Lee lạnh',
                'description'=>'Lee kéo chăn để đắp',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'thumbnail' => '054_kjblmn',
                'thumbnail_by'=> 14,
                'title'=>'Lee ngứa rắng',
                'description'=>'Lee cắt cái vỏ chăn',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'thumbnail' => '133_rajjyl',
                'thumbnail_by'=> 14,
                'title'=>'Lee trầm tư',
                'description'=>'Lee đang suy nghĩ gì thế',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'thumbnail' => '144_subx7o',
                'thumbnail_by'=> 14,
                'title'=>'Lee đang chơi cùng Kem',
                'description'=>'Lee cảm thấy vui vẻ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'thumbnail' => '143_ffusrw',
                'thumbnail_by'=> 14,
                'title'=>'Lee đang chơi cùng Kem',
                'description'=>'Lee cảm thấy vui vẻ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'thumbnail' => '271_nuba04',
                'thumbnail_by'=> 14,
                'title'=>'Lee cảm thấy buồn nôn',
                'description'=>'Nhưng lee không nôn được',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'thumbnail' => '262_cnde1k',
                'thumbnail_by'=> 14,
                'title'=>'Lee dỗi ',
                'description'=>'Lee ko muốn ăn',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'thumbnail' => '287_lmni4x',
                'thumbnail_by'=> 14,
                'title'=>'Lee chơi với Jerry',
                'description'=>'Lee cảm thấy vui',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'thumbnail' => 'IMG_9662_cucwch',
                'thumbnail_by'=> 14,
                'title'=>'Lee muốn ra ngoài đi chơi',
                'description'=>'Nhưng lee lại không được đi chơi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'thumbnail' => '285_d0zcmq',
                'thumbnail_by'=> 14,
                'title'=>'Lee chơi với Jerry',
                'description'=>'Lee cảm thấy vui',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'thumbnail' => 'IMG_9661_vk2sos',
                'thumbnail_by'=> 14,
                'title'=>'lee xin ăn',
                'description'=>'Ai cho lee ăn với ><',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'thumbnail' => 'IMG_9755_mxocir',
                'thumbnail_by'=> 14,
                'title'=>'Lee cảm thấy đáng yêu ><',
                'description'=>'Mọi người có thấy vậy ko ?',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'thumbnail' => 'IMG_9745_fhqklw',
                'thumbnail_by'=> 14,
                'title'=>'Lee cảm thấy buồn',
                'description'=>'Ai chơi cùng lee hông',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'thumbnail' => 'IMG_9757_nzv4zu',
                'thumbnail_by'=> 14,
                'title'=>'Lee thật đáng yêu',
                'description'=>'Phải vậy không mọi người',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'thumbnail' => 'IMG_9758_usg0ep',
                'thumbnail_by'=> 14,
                'title'=>'Ahihi',
                'description'=>'Lee thật dễ thương',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'thumbnail' => 'IMG_9741_oxsocb',
                'thumbnail_by'=> 14,
                'title'=>'Ahihi',
                'description'=>'Lee thật dễ thương',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'thumbnail' => 'IMG_1454_sywqee',
                'thumbnail_by'=> 15,
                'title'=>'Lee có anh em nè',
                'description'=>'Thật là vui quá',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'thumbnail' => '189_prg3mz',
                'thumbnail_by'=> 15,
                'title'=>'Lee có người chơi cùng nè',
                'description'=>'Ai chơi cùng nữa ko nào',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'thumbnail' => '7IMG_1539_l0peyn',
                'thumbnail_by'=> 15,
                'title'=>'Lee có người chơi cùng nè',
                'description'=>'Ai chơi cùng nữa ko nào',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'thumbnail' => '111_stlnqg',
                'thumbnail_by'=> 15,
                'title'=>'Lee đang cmr thấy rất vui',
                'description'=>'Chơi cùng lee thì ai cũng như vậy nè',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'thumbnail' => '121_fyztvn',
                'thumbnail_by'=> 15,
                'title'=>'Lee cảm thấy vui hơn bao giờ hết',
                'description'=>'Có vui như lee không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'thumbnail' => 'IMG_1749_oybhjl',
                'thumbnail_by'=> 15,
                'title'=>'Lee cảm thấy vui hơn bao giờ hết',
                'description'=>'Có vui như lee không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'thumbnail' => 'IMG_1674_xtanze',
                'thumbnail_by'=> 15,
                'title'=>'Lee lúc còn nhỏ ',
                'description'=>'Có ai thấy lee đáng yêu không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'thumbnail' => 'IMG_2529_e4mb9s',
                'thumbnail_by'=> 15,
                'title'=>'Lee bên cạnh bông hoa',
                'description'=>'Có ai thấy rất hợp với lee không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'thumbnail' => 'IMG_1749_oybhjl',
                'thumbnail_by'=> 16,
                'title'=>'Lee bên cạnh bông hoa',
                'description'=>'Có ai thấy rất hợp với lee không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'thumbnail' => 'IMG_1777_v2je8a',
                'thumbnail_by'=> 16,
                'title'=>'Lee bên cạnh bông hoa',
                'description'=>'Có ai thấy rất hợp với lee không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'thumbnail' => 'IMG_1754_cbhunn',
                'thumbnail_by'=> 16,
                'title'=>'Lee được nựng ',
                'description'=>'Lee muốn nựng thêm cơ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'thumbnail' => 'IMG_1788_qc5wq9',
                'thumbnail_by'=> 16,
                'title'=>'Lee muốn được ôm',
                'description'=>'Có ai dang rảnh tay không ',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'thumbnail' => 'IMG_1789_blhezo',
                'thumbnail_by'=> 16,
                'title'=>'Lee cảm thấy chán',
                'description'=>'Ai đưa lee đi chơi đi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'thumbnail' => 'IMG_2603_edat8w',
                'thumbnail_by'=> 16,
                'title'=>'Lee đang được nựng',
                'description'=>'Lee cảm thấy vui',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'thumbnail' => 'IMG_2634_ap5sjw',
                'thumbnail_by'=> 16,
                'title'=>'Lee rất dễ thương',
                'description'=>'Có ai cũng thấy vậy không',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'thumbnail' => 'IMG_2682_on8nyp',
                'thumbnail_by'=> 16,
                'title'=>'Lee thấy cô đơn',
                'description'=>'Ai đó chơi với lee đi',
                'created_at' => Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id'=>68,
                'thumbnail'=>'images_8_i71vzt',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn đang chơi xích đu',
                'description'=>'Ai chơi với Catlyn không',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>69,
                'thumbnail'=>'images_7_kjp8o6',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn cảm thấy ngại',
                'description'=>'Đừng trêu catlyn nha',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>70,
                'thumbnail'=>'images_9_br6rdj',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn đang cảm thấy rất vui',
                'description'=>'Có ai vui cung catlyn không',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>71,
                'thumbnail'=>'images_10_n3snkr',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn ăn hoa ',
                'description'=>'Đừng ai bắt trước Catlyn nha',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>72,
                'thumbnail'=>'images_12_qzvrlz',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn mới ngủ dậy',
                'description'=>'Thật là sảng khoái',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>73,
                'thumbnail'=>'images_11_on27kz',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn hình như hơi tăng cân',
                'description'=>'Mọi người nói thật cho catlyn đi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>74,
                'thumbnail'=>'phoi-giong-cho-cho-Pug-1_ibjwye',
                'thumbnail_by'=> 1,
                'title'=>'Catlyn đang nhìn ',
                'description'=>'Nhìn Catlyn chi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>75,
                'thumbnail'=>'images_20_cwvxd0',
                'thumbnail_by'=> 2,
                'title'=>'Yi có anh em sinh đôi',
                'description'=>'Đố ai thấy khác ở đâu đấy',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>76,
                'thumbnail'=>'images_19_jjhbng',
                'thumbnail_by'=> 2,
                'title'=>'Yi thật chi thức',
                'description'=>'Có ai thấy hợn với yi không',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>77,
                'thumbnail'=>'images_21_zpfpoq',
                'thumbnail_by'=> 2,
                'title'=>'Yi đang trâm tư  ',
                'description'=>'Yi đang nghỉ là tối nay ăn gì ?',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>78,
                'thumbnail'=>'images_22_hqrmef',
                'thumbnail_by'=> 2,
                'title'=>'Yi ngơ ngác ',
                'description'=>'Yi đang chăm chú nhìn cái gì đấy ?',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>79,
                'thumbnail'=>'images_eerxrf',
                'thumbnail_by'=> 2,
                'title'=>'Yi đi chơi',
                'description'=>'Một ngày đẹp trời Yi tung tăng chạy ra đồng',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>80,
                'thumbnail'=>'images_49_b6cndo',
                'thumbnail_by'=> 2,
                'title'=>'Yi đi chụp hình',
                'description'=>'Yi đang tạo giáng thật là đáng yêu ',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>81,
                'thumbnail'=>'images_dpi4kv',
                'thumbnail_by'=> 3,
                'title'=>'Ben sợ hãi',
                'description'=>'Ben chạy vào góc tường ngồi sợ hãi một mình',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>82,
                'thumbnail'=>'images_1_wxed0s',
                'thumbnail_by'=> 3,
                'title'=>'Ben ngồi chơi',
                'description'=>'Ben đang ngồi nhìn cái gì đấy',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>83,
                'thumbnail'=>'images_2_nmp0sg',
                'thumbnail_by'=> 3,
                'title'=>'Ben đi chơi',
                'description'=>'Ben đang đi dạo quanh cùng bạn gái !',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>84,
                'thumbnail'=>'images_3_p80dcj',
                'thumbnail_by'=> 3,
                'title'=>'Ben đi chơi',
                'description'=>'Ben dđang tung tăng dạo chơi trong vườn ',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>85,
                'thumbnail'=>'images_4_biku6h',
                'thumbnail_by'=> 3,
                'title'=>'Ben đi chơi',
                'description'=>'Ben đang được chụp hình trong lúc đang ngồi nghỉ chân ',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>86,
                'thumbnail'=>'images_5_oab5ih',
                'thumbnail_by'=> 3,
                'title'=>'Ben mới được đi làm đẹp',
                'description'=>'Ben đang đi khoe bộ lông mới của mình',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>87,
                'thumbnail'=>'images_6_khpwfh',
                'thumbnail_by'=> 3,
                'title'=>'Ben mới được đi làm đẹp',
                'description'=>'Ben đang đi khoe bộ lông mới của mình',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>88,
                'thumbnail'=>'images_tgqyad',
                'thumbnail_by'=> 4,
                'title'=>'Panda đi chụp hình',
                'description'=>'Panda đang tạo dáng để được chụp hình',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>89,
                'thumbnail'=>'images_pv5p5v',
                'thumbnail_by'=> 4,
                'title'=>'Panda đang bất ngờ',
                'description'=>'Panda đang bất ngờ khi bị bế lên để chụp hình',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>90,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>91,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>92,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>93,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>94,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>95,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>96,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>97,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>98,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>99,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],
            [
                'id'=>100,
                'thumbnail'=>'images_f2asor',
                'thumbnail_by'=> 4,
                'title'=>'Panda mới thay đồ mới',
                'description'=>'Panda chuẩn bị được đưa đi dạo chơi',
                'created_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s')
            ],


        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }

}
